# NGINX OSS webserver with tools
# NGINX Basics, Jan 2024
# Chris Akker, Shouvik Dutta
version: '3.3'
services:
  nginx-oss:                  # NGINX OSS Webserver
    hostname: nginx-oss
    container_name: nginx-oss
    build: nginx-oss          # Build new container, using /nginx-oss/Dockerfile
    volumes:                  # Sync these folders to container
        - ./nginx-oss/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx-oss/etc/nginx/conf.d:/etc/nginx/conf.d
        - ./nginx-oss/etc/nginx/includes:/etc/nginx/includes
        - ./nginx-oss/usr/share/nginx/html:/usr/share/nginx/html
        - ./nginx-oss/etc/ssl:/etc/ssl
    ports:
        - 80:80       # Open for HTTP
        - 443:443     # Open for HTTPS
        - 9000:9000   # Open for stub status page
    restart: always     
     