# NGINX Plus Proxy
# Juiceshop web application
# NGINX Basics Caching, Feb 2024
# Chris Akker, Shouvik Dutta
#
version: '3.3'
services:
# NGINX Plus Load Balancer, Cache       
  nginx-plus:
      hostname: nginx-plus
      container_name: nginx-plus
      build: nginx-plus
      volumes:
        - ./nginx-plus/etc/nginx/conf.d:/etc/nginx/conf.d        # Copy these folders to container
        - ./nginx-plus/etc/nginx/includes:/etc/nginx/includes
        - ./nginx-plus/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      links:
          - juice1:juice1
          - juice2:juice2
          - juice3:juice3
      ports:
          - 80:80
          - 443:443
          - 9000:9000
      restart: always
# Juiceshop web application containers
  juice1:
      hostname: juice1
      container_name: juice1
      image: bkimminich/juice-shop            # Image from Docker Hub
      ports:
        - "3000"
  juice2:
      hostname: juice2
      container_name: juice2
      image: bkimminich/juice-shop
      ports:
        - "3000"
  juice3:
      hostname: juice3
      container_name: juice3
      image: bkimminich/juice-shop
      ports:
        - "3000"

