# Use the multi-stage build to add necessary dynamic modules from F5 NGINX private registry (Optional)
# FROM private-registry.nginx.com/nginx-plus/modules:r34-headers_more-debian as headers_more-base
# FROM private-registry.nginx.com/nginx-plus/modules:r34-otel-debian as otel-base

# Use the NGINX agent image from F5 NGINX private registry 
FROM private-registry.nginx.com/nginx-plus/rootless-agent:r34-debian-bookworm

# Use this section to COPY the dynamic modules to the base image (Optional)
# COPY --from=headers_more-base / /
# COPY --from=otel-base / /

# Set some default environment variables (can be overridden at runtime)
ENV NGINX_LICENSE_JWT=""
ENV NGINX_AGENT_SERVER_GRPCPORT=443
ENV NGINX_AGENT_SERVER_HOST=agent.connect.nginx.com
ENV NGINX_AGENT_SERVER_TOKEN=""
ENV NGINX_AGENT_TLS_ENABLE=true

# Copy NGINX Configs as it is not being mounted
COPY --chown=nginx:nginx ./etc/nginx/conf.d /etc/nginx/conf.d
COPY --chown=nginx:nginx ./etc/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --chown=nginx:nginx ./etc/nginx/includes /etc/nginx/includes
COPY --chown=nginx:nginx ./etc/ssl/nginx/nginx-repo.* /etc/ssl/nginx/