global:
  scrape_interval: 15s 
  
  external_labels:
    monitor: 'nginx-monitor'

scrape_configs:  
  - job_name: 'prometheus'
    
    scrape_interval: 5s

    static_configs:
      - targets: ['nginx-plus:9113']  # NGINX Plus container
