# NGINX Plus webserver with tools
# NGINX Plus Basics, Nov 2024
# Chris Akker, Shouvik Dutta, Adam Currier
#
services:
  nginx-plus:                  # NGINX Plus Webserver
    hostname: nginx-plus
    container_name: nginx-plus
    image: nginx-plus:workshop
    #build: ./nginx-plus          # Build new container, using /nginx-oss/Dockerfile
    volumes:                  # Sync these folders to container
        - ./nginx-plus/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx-plus/etc/nginx/conf.d:/etc/nginx/conf.d
        - ./nginx-plus/etc/nginx/includes:/etc/nginx/includes
        - ./nginx-plus/usr/share/nginx/html:/usr/share/nginx/html
        - ./nginx-plus/etc/ssl:/etc/ssl
    ports:
        - 80:80       # Open for HTTP
        - 443:443     # Open for HTTPS
        - 9000:9000   # Open for API / dashboard page
    restart: always     
     