# NGINX Plus Proxy with tools build
# NGINX webservers with ingress-demo pages
# NGINX Basics, Nov 2024
# Chris Akker, Shouvik Dutta, Adam Currier
#
services:
  nginx-plus:                  # NGINX Plus Web / Load Balancer
    hostname: nginx-plus
    container_name: nginx-plus
    #build: ./nginx-plus          # Build new container, using /nginx-plus/Dockerfile
    image: nginx-plus:workshop          # Run nginx-plus container
    volumes:                      # Copy these files/folders to container 
        - ./nginx-plus/etc/nginx/conf.d:/etc/nginx/conf.d
        - ./nginx-plus/etc/nginx/includes:/etc/nginx/includes
        - ./nginx-plus/usr/share/nginx/html:/usr/share/nginx/html
        - ./nginx-plus/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ../nginx-repo.jwt:/etc/nginx/license.jwt      # Copy JWT Token to fulfill licensing requirement
    ports:
        - 80:80       # Open for HTTP
        - 443:443     # Open for HTTPS
        - 9000:9000   # Open for Plus Dashboard page / API
    restart: always     
  web1:
      hostname: web1
      container_name: web1
      image: nginxinc/ingress-demo            # Image from Docker Hub
      ports:
        - "80"                                # Open for HTTP
        - "443"                               # Open for HTTPS
  web2:
      hostname: web2
      container_name: web2
      image: nginxinc/ingress-demo
      ports:
        - "80"
        - "433"
  web3:
      hostname: web3
      container_name: web3
      image: nginxinc/ingress-demo
      ports:
        - "80"
        - "443"  