# NGINX Plus Proxy with tools build
# NGINX webservers with ingress-demo pages
# NGINX Basics, Nov 2024
# Chris Akker, Shouvik Dutta, Adam Currier
#
services:
  workshop11:                  # NGINX Plus Web / Load Balancer
    environment:
      NGINX_AGENT_SERVER_HOST: "agent.connect.nginx.com"
      NGINX_AGENT_SERVER_GRPCPORT: "443"
      NGINX_AGENT_TLS_ENABLE: "true"
      NGINX_AGENT_SERVER_TOKEN: "iStZKfCF398qYoVxv1I6XTScS9c9lhSQZvbJymXF2k8="  
    hostname: workshop11
    container_name: workshop11
    image: nginx-plus:workshop  # From Lab1
    volumes:                    # Sync these folders to container
        - ./nginx-plus/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx-plus/etc/nginx/conf.d:/etc/nginx/conf.d
        - ./nginx-plus/etc/nginx/includes:/etc/nginx/includes
        - ./nginx-plus/usr/share/nginx/html:/usr/share/nginx/html
    ports:
        - "80"      # Open for HTTP
        - "443"     # Open for HTTPS
        - "9000"    # Open for API / Dashboard page
        - "9113"    # Open for Prometheus Scraper page
    restart: always
  #
  workshop12:                  # NGINX Plus Web / Load Balancer
    hostname: workshop12
    container_name: workshop12
    image: nginx-plus:workshop  # From Lab1
    volumes:                    # Sync these folders to container
        - ./nginx-plus/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx-plus/etc/nginx/conf.d:/etc/nginx/conf.d
        - ./nginx-plus/etc/nginx/includes:/etc/nginx/includes
        - ./nginx-plus/usr/share/nginx/html:/usr/share/nginx/html
    ports:
        - "80"       # Open for HTTP
        - "443"      # Open for HTTPS
        - "9000"     # Open for API / Dashboard page
        - "9113"     # Open for Prometheus Scraper page
    restart: always      
  #
  web1:
      hostname: web1
      container_name: web1
      image: nginxinc/ingress-demo            # Image from Docker Hub
      ports:
        - "80"                                # Open for HTTP
        - "443"                               # Open for HTTPS
  web2:
      hostname: web2
      container_name: web2
      image: nginxinc/ingress-demo
      ports:
        - "80"
        - "433"
  web3:
      hostname: web3
      container_name: web3
      image: nginxinc/ingress-demo
      ports:
        - "80"
        - "443"
